server:
  port: 8083
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3307/test
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

